/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/cloud.glb 
Author: KiwiBiwii (https://sketchfab.com/KiwiBiwii)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cloud-cfab6d1ad5134559ab33ab61f07240ba
Title: Cloud
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud(props: any) {
  const { nodes, materials } = useGLTF('./models/cloud.glb')
  return (
    <group {...props} dispose={null}>
      {/* @ts-ignore */}
      <mesh geometry={nodes.Object_2.geometry} material={materials['Paint_-_Metallic_Silver']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/cloud.glb')
