/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/avro.gltf 
Author: helijah (https://sketchfab.com/helijah)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/avro-cf-105-arrow-7f35555299ef47e48851901a98669d9e
Title: Avro CF-105 Arrow
*/

//@ts-nocheck

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Avro(props) {
  const { nodes, materials } = useGLTF('./models/avro.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.DefaultWhite_NONE} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['DefaultWhite_radar.png']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.DefaultWhite} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['DefaultWhite_ai.png']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['DefaultWhite_alt.png']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['DefaultWhite_asi.png']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['DefaultWhite_divers.png']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['DefaultWhite_exh.png']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['DefaultWhite_flight-indicator.png']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['DefaultWhite_fuel.png']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['DefaultWhite_fuelflow.png']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['DefaultWhite_gmeter.png']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['DefaultWhite_interior.png']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['DefaultWhite_mag-compass.png']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['DefaultWhite_oil.png']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['DefaultWhite_panel.png']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['DefaultWhite_pedals.png']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['DefaultWhite_ralt.png']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['DefaultWhite_rmi.png']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['DefaultWhite_rpm.png']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['DefaultWhite_seat.png']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['DefaultWhite_stick.png']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['DefaultWhite_texture.png']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['DefaultWhite_texture.png']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['DefaultWhite_texture.png']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['DefaultWhite_texture.png']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['DefaultWhite_turn.png']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['DefaultWhite_vsi.png']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Transparent} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.transparentExt} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/avro.gltf')
