/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

//@ts-nocheck

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Background(props) {
  const { nodes, materials } = useGLTF("./models/stage.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.hill_01.geometry}
        material={materials["Material.036"]}
        position={[0.12, 1.6, -18.89]}
        rotation={[0, -0.14, 0]}
        scale={[2.39, 1.76, 1.42]}
      >
      </mesh>
      <mesh
        geometry={nodes.hill_02.geometry}
        material={materials["Material.035"]}
        position={[3.52, 2.32, -17.42]}
        rotation={[0, 0.37, 0]}
        scale={[3.06, 2.5, 1.81]}
      />
      <mesh
        geometry={nodes.stone_01.geometry}
        material={materials["Material.020"]}
        position={[6.12, 0.11, 5.67]}
        rotation={[0.07, 0.56, -0.3]}
        scale={[0.19, 0.13, 0.15]}
      >
        <mesh
          geometry={nodes.stone_02.geometry}
          material={materials["Material.020"]}
          position={[-2.24, -1.09, -0.31]}
          rotation={[0.76, -0.79, 0.82]}
          scale={[1.27, 0.92, 0.92]}
        />
      </mesh>
      <mesh
        geometry={nodes.stone_04.geometry}
        material={materials["Material.020"]}
        position={[-5.5, 0.14, 5.94]}
        rotation={[0.02, 0.67, 0.81]}
        scale={[0.18, 0.12, 0.14]}
      >

      </mesh>


      <mesh
        geometry={nodes.bush_01.geometry}
        material={materials["Material.013"]}
        position={[3.21, 0.13, -4.35]}
        rotation={[0, -0.29, -0.89]}
        scale={0.12}
      />
 
      <mesh
        geometry={nodes.cloud.geometry}
        material={nodes.cloud.material}
        position={[-5.11, 1.26, -23.57]}
        scale={1.82}
      />
 

      <mesh
        geometry={nodes.hill_02001.geometry}
        material={materials["Material.035"]}
        position={[-3.06, 1.87, -20.31]}
        rotation={[Math.PI, -0.53, Math.PI]}
        scale={[2.27, 1.85, 1.34]}
      />
      <mesh
        geometry={nodes.cloud001.geometry}
        material={nodes.cloud001.material}
        position={[1.4, 2.1, -24.37]}
        rotation={[0, 0.22, 0]}
        scale={1.4}
      />
      <mesh
        geometry={nodes.cloud002.geometry}
        material={nodes.cloud002.material}
        position={[9.07, 1.58, -24.14]}
        rotation={[0, 0.22, 0]}
        scale={2.41}
      />
      <mesh
        geometry={nodes.table_01.geometry}
        material={materials["Material.021"]}
        position={[-7.54, 0.19, -6.85]}
        rotation={[0.86, 1.07, 2.44]}
        scale={[0.06, 0.2, 0.06]}
      >
        <mesh
          geometry={nodes["01"].geometry}
          material={materials["Material.033"]}
          position={[9.91, -2.86, 9.79]}
          rotation={[1.34, 1.09, 2.17]}
          scale={[1.78, 0.85, 1.82]}
        />
        <mesh
          geometry={nodes["02"].geometry}
          material={materials["Material.031"]}
          position={[-2.08, -2.07, 4.35]}
          rotation={[1.34, 1.09, 2.17]}
          scale={[1.38, 0.47, 1.41]}
        />
        <mesh
          geometry={nodes["03"].geometry}
          material={materials["Material.032"]}
          position={[13.63, -3.76, 12.76]}
          rotation={[1.34, 1.09, 2.17]}
          scale={[0.86, 0.7, 0.88]}
        />
        <mesh
          geometry={nodes["04"].geometry}
          material={nodes["04"].material}
          position={[13.74, -4.3, 11.34]}
          rotation={[1.31, 1.07, 2.36]}
          scale={[0.09, 0.78, 0.09]}
        />
        <mesh
          geometry={nodes["05"].geometry}
          material={materials["Material.034"]}
          position={[3.57, -3.21, 9.92]}
          rotation={[-0.65, 0.16, 0.84]}
          scale={[7.53, 9.27, 4.77]}
        />
        <mesh
          geometry={nodes["06"].geometry}
          material={materials["Material.034"]}
          position={[0.67, -2.17, 1.98]}
          rotation={[-1.22, -0.44, -0.54]}
          scale={[9.05, 9.14, 3.08]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/stage.gltf");