/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/flagindia.gltf 
Author: alakeshkakati125 (https://sketchfab.com/alakeshkakati125)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flag-of-india-d0a955283a5248d1bbff5fc4ed9a1877
Title: Flag of India
*/

// @ts-nocheck

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function FlagIndia(props) {
  const { nodes, materials } = useGLTF('./models/flagindia.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.root_Material_95_0.geometry} material={materials.Material_95} position={[0.881, 1.624, 0.861]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.088, 0.857, 0.368]} />
      <mesh geometry={nodes.root_Material_97_0.geometry} material={materials.Material_97} position={[1.308, 0.277, 0.863]} scale={0.001} />
      <mesh geometry={nodes.root_Material_99_0.geometry} material={materials.Material_99} position={[1.311, 0.325, 0.862]} scale={0.001} />
      <mesh geometry={nodes.root_Material_101_0.geometry} material={materials.Material_101} position={[1.311, 1.139, 0.865]} scale={[0.001, 0.002, 0.001]} />
      <mesh geometry={nodes.root_Material_79_0.geometry} material={materials.Material_79} position={[1.312, 1.979, 0.864]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
    </group>
  )
}

useGLTF.preload('./models/flagindia.gltf')
