/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/cntower.gltf 
Author: jayden.ot111 (https://sketchfab.com/jayden.ot111)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cn-tower-7abf3849d3b1460bb8332e473275a249
Title: cn-tower
*/

//@ts-nocheck

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CNTower(props) {
  const { nodes, materials } = useGLTF('./models/cntower.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 35.491, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[34.836, 34.836, 20.902]}>
          <mesh geometry={nodes.Cylinder_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Cylinder_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[0, 1358.058, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[132.077, 132.077, 21.934]}>
          <mesh geometry={nodes.Cylinder002_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cylinder002_Material009_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cylinder002_Material007_0.geometry} material={materials['Material.007']} />
        </group>
        <mesh geometry={nodes.Cube_Material008_0.geometry} material={materials['Material.008']} position={[0, 29.66, -107.17]} rotation={[-Math.PI / 2, 0, 0]} scale={[18.783, 100, 16.473]} />
        <mesh geometry={nodes.Cube001_Material008_0.geometry} material={materials['Material.008']} position={[-73.538, 29.66, 78.847]} rotation={[-Math.PI / 2, 0, 2.434]} scale={[18.783, 100, 16.473]} />
        <mesh geometry={nodes.Cube002_Material008_0.geometry} material={materials['Material.008']} position={[84.044, 29.66, 72.702]} rotation={[-Math.PI / 2, 0, -2.279]} scale={[18.783, 100, 16.473]} />
        <mesh geometry={nodes.Torus001__0.geometry} material={materials['Torus.001__0']} position={[0, 1272.35, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 135.461]} />
        <mesh geometry={nodes.Cylinder001__0.geometry} material={materials['Torus.001__0']} position={[0, 1316.038, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 14.017]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/cntower.gltf')
