/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/diya.gltf 
Author: TheDesigner (https://sketchfab.com/Coolhitz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diwali-candle-eff262d75ab9498581040b31f76df348
Title: Diwali Candle
*/

// @ts-nocheck

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Diya(props) {
  const { nodes, materials } = useGLTF('./models/diya.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.256, 0]} rotation={[0, 0.907, 0]} scale={2.216}>
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.003']} position={[0, 0.27, 0]} rotation={[0, 0.579, 0]} scale={[1.554, 0.078, 1.554]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.004']} position={[0, 0.192, 0]} rotation={[0, 0.579, 0]} scale={[0.978, 0.096, 0.978]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.005']} position={[0, 0.552, 0]} rotation={[0, 0.579, -Math.PI]} scale={[-0.487, 0.032, 0.487]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Fire_Generator} position={[0, 0.873, 0]} rotation={[0, 0.579, 0]} scale={0.19} />
    </group>
  )
}

useGLTF.preload('./models/diya.gltf')
