/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/gada.glb 
*/

// @ts-nocheck

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Gada(props) {
  const { nodes, materials } = useGLTF('./models/gada.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.061, -0.024, -0.001]} rotation={[-Math.PI / 2, -0.201, 0]} scale={0.001}>
        <mesh geometry={nodes.Cone_2.geometry} material={materials['Gold Satin']} position={[202.969, -1, 85]} rotation={[0, Math.PI / 2, 0]} scale={[0.226, 0.226, 0.259]} />
        <mesh geometry={nodes.Sphere_4.geometry} material={materials['Gold Satin 6']} position={[131.969, 13, 99]} rotation={[2.356, 0, 0]} scale={[15.761, 18.478, 4.348]} />
        <mesh geometry={nodes.Sphere_3.geometry} material={materials['Gold Satin 5']} position={[131.969, 14, 71]} rotation={[Math.PI / 4, 0, 0]} scale={[15.761, 18.478, 4.348]} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials['Gold Satin 4']} position={[131.969, 19, 85]} rotation={[Math.PI / 2, 0, 0]} scale={[15.761, 18.478, 4.348]} />
        <mesh geometry={nodes.Sphere_1.geometry} material={materials['Gold Satin 1']} position={[131.969, 0, 65]} scale={[15.761, 18.478, 4.348]} />
        <mesh geometry={nodes.Sphere.geometry} material={materials['Gold Satin']} position={[-215.031, -1, 70]} scale={1.376} />
        <mesh geometry={nodes.Box_1.geometry} material={materials.Balboa} position={[98.969, -1, 85]} rotation={[0, -Math.PI / 2, 0]} scale={[0.313, 0.313, 1.003]} />
        <mesh geometry={nodes.Cone_1.geometry} material={materials['Gold Satin 3']} position={[75.969, -1, 85]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cone.geometry} material={materials['Gold Satin']} position={[87.969, -1, 85]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Torus_3.geometry} material={materials['Gold Satin 2']} position={[170.209, 0, 85]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Torus_2.geometry} material={materials['Gold Satin']} position={[178.209, 0, 85]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Torus_12.geometry} material={materials['Gold Satin 15']} position={[-202.031, 0, 80]} rotation={[0, Math.PI / 4, 0]} scale={[0.769, 0.769, 0.953]} />
        <mesh geometry={nodes.Torus_11.geometry} material={materials['Gold Satin 14']} position={[-172.031, 0, 80]} rotation={[0, Math.PI / 4, 0]} scale={[0.828, 0.828, 0.953]} />
        <mesh geometry={nodes.Torus_10.geometry} material={materials['Gold Satin 13']} position={[-142.031, 0, 80]} rotation={[0, Math.PI / 4, 0]} scale={[0.888, 0.888, 0.977]} />
        <mesh geometry={nodes.Torus_9.geometry} material={materials['Gold Satin 12']} position={[-112.031, 0, 80]} rotation={[0, Math.PI / 4, 0]} scale={[0.947, 0.947, 0.977]} />
        <mesh geometry={nodes.Torus_8.geometry} material={materials['Gold Satin 11']} position={[-82.031, 0, 80]} rotation={[0, Math.PI / 4, 0]} scale={[1.006, 1.006, 0.977]} />
        <mesh geometry={nodes.Torus_7.geometry} material={materials['Gold Satin 10']} position={[-52.031, 0, 80]} rotation={[0, Math.PI / 4, 0]} scale={[1.065, 1.065, 1]} />
        <mesh geometry={nodes.Torus_6.geometry} material={materials['Gold Satin 9']} position={[-22.031, 0, 80]} rotation={[0, Math.PI / 4, 0]} scale={[1.124, 1.124, 1]} />
        <mesh geometry={nodes.Torus_5.geometry} material={materials['Gold Satin 8']} position={[7.969, 0, 80]} rotation={[0, Math.PI / 4, 0]} scale={[1.183, 1.183, 1]} />
        <mesh geometry={nodes.Torus_4.geometry} material={materials['Gold Satin 7']} position={[37.969, 0, 80]} rotation={[0, Math.PI / 4, 0]} scale={[1.243, 1.243, 1]} />
        <mesh geometry={nodes.Torus_1.geometry} material={materials['Gold Satin']} position={[104.969, 0, 85]} rotation={[0, Math.PI / 2, 0]} scale={[0.993, 0.993, 1]} />
        <mesh geometry={nodes.Torus.geometry} material={materials.Balboa} position={[67.969, -1, 85]} rotation={[0, Math.PI / 2, 0]} scale={[0.998, 0.998, 1]} />
      </group>
      <PerspectiveCamera makeDefault={false} far={82.019} near={0.015} fov={20} position={[0.224, 0.065, 1.142]} rotation={[0.038, 0.118, -0.004]} />
    </group>
  )
}

useGLTF.preload('./models/gada.glb')
