/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/iceberg.glb 
Author: phaholyut_s (https://sketchfab.com/phaholyut_s)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-iceberg-scene-d48e92e570204adbaac185d7920708be
Title: Low Poly Iceberg Scene
*/

// @ts-nocheck

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Iceberg(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./models/iceberg.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e630e7fd7a8040388f27e4b33bfb0044fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Iceberg" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Iceberg_Iceberg_0" geometry={nodes.Iceberg_Iceberg_0.geometry} material={materials.Iceberg} />
                </group>
                <group name="Small_Platform" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Small_Platform_Iceberg_0" geometry={nodes.Small_Platform_Iceberg_0.geometry} material={materials.Iceberg} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/iceberg.glb')
