/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/indiagate.gltf 
*/

//@ts-nocheck

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function IndiaGate(props) {
  const { nodes, materials } = useGLTF('./models/indiagate.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.India_Gate_1.geometry} material={materials['Material 2']} />
      <mesh geometry={nodes.India_Gate_2.geometry} material={materials['Material 1']} />
    </group>
  )
}

useGLTF.preload('./models/indiagate.gltf')
