/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/naruto.glb 
Author: taj_tajima (https://sketchfab.com/taj_tajima)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/naruto-fan-art-6436c3e8828c441cbfb8896628d8bdac
Title: Naruto fan art
*/

//@ts-nocheck

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/naruto.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube_0" position={[-0.071, -3.262, -1.466]} rotation={[0.119, 0, 0]} scale={1.052}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube001_1" position={[5.743, -0.285, -6.079]} rotation={[1.476, -0.118, 0.001]} scale={1.052}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube002_2" position={[-4.746, -1.728, -0.057]} rotation={[1.313, -1.058, 0.157]} scale={1.052}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
              </group>
              <group name="Plane_3" position={[-0.017, -7.33, -5.771]} scale={14.826}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material_0} />
              </group>
              <group name="metarig_57" position={[0, -0.818, 0]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="naruto_mesh_54_correction" position={[0, 0.818, 0]}>
                    <group name="naruto_mesh_54" />
                  </group>
                  <skinnedMesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.Material} skeleton={nodes.Object_62.skeleton} />
                </group>
              </group>
              <group name="metarig001_105" position={[2.002, 3.174, -5.222]}>
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <group name="naruto_mesh001_104_correction" position={[-2.002, -3.174, 5.222]}>
                    <group name="naruto_mesh001_104" />
                  </group>
                  <skinnedMesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.Material} skeleton={nodes.Object_114.skeleton} />
                </group>
              </group>
              <group name="metarig002_153" position={[-4.171, 1.119, -6.422]} rotation={[0, -0.947, 0]}>
                <group name="GLTF_created_2">
                  <primitive object={nodes.GLTF_created_2_rootJoint} />
                  <group name="naruto_mesh002_152_correction" position={[7.649, -1.119, 0.366]} rotation={[0, 0.947, 0]}>
                    <group name="naruto_mesh002_152" />
                  </group>
                  <skinnedMesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.Material} skeleton={nodes.Object_166.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/naruto.glb')
