/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/store.glb 
Author: Zeeshan Khan (https://sketchfab.com/zeekhan733)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-store-building-a26a5528823945a99386a34d92313f6c
Title: Low Poly Store Building
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Store(props: any) {
  const { nodes, materials } = useGLTF('./models/store.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={51.446}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              {/* @ts-ignore */}

          <mesh geometry={nodes.typeMesh2_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                {/* @ts-ignore */}

          <mesh geometry={nodes.typeMesh2_lambert2_0.geometry} material={materials.lambert2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/store.glb')
