/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/iceberg.glb 
Author: phaholyut_s (https://sketchfab.com/phaholyut_s)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-iceberg-scene-d48e92e570204adbaac185d7920708be
Title: Low Poly Iceberg Scene
*/

// @ts-nocheck

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Water(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./models/iceberg.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
                <group name="Water" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Water_Water_0" geometry={nodes.Water_Water_0.geometry} material={materials.Water} />
                </group>
    </group>
  )
}

useGLTF.preload('./models/iceberg.glb')
